external:
  publicapi:
    apiKey: ${PUBLIC_API_KEY}

  kepco:
    kepcokey: ${KEPCO_API_KEY}
    defaultCodeTy: cityCd
    basedataurl: https://bigdata.kepco.co.kr/openapi/v1/commonCode.do
    usagedataurl: https://bigdata.kepco.co.kr/openapi/v1/powerUsage/houseAve.do

  kca:
    basedataurl: http://openapi.price.go.kr/openApiImpl/ProductPriceInfoService/getStandardInfoSvc.do
    totaldiv: http://openapi.price.go.kr/openApiImpl/ProductPriceInfoService/getStandardInfoSvc.do
    storeinfo: http://openapi.price.go.kr/openApiImpl/ProductPriceInfoService/getStoreInfoSvc.do?
    productinfo: http://openapi.price.go.kr/openApiImpl/ProductPriceInfoService/getProductInfoSvc.do?
    priceinfo: http://openapi.price.go.kr/openApiImpl/ProductPriceInfoService/getProductPriceInfoSvc.do?

  weather:
    shorttime: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst

  kakao:
    searchkeyword: https://dapi.kakao.com/v2/local/search/keyword
    restKey: ${KAKAO_REST_KEY}

spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  cache:
    type: redis

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
